# Generated by Django 2.1.7 on 2019-03-15 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20190315_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=31, primary_key=True, serialize=False),
        ),
    ]
