# Generated by Django 2.1.7 on 2019-03-15 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20190315_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_secret',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=31),
        ),
    ]
